// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameAdminUserAdminRole = "admin_user_admin_role"

// AdminUserAdminRole mapped from table <admin_user_admin_role>
type AdminUserAdminRole struct {
	ID          int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	AdminUserID int64         `gorm:"column:admin_user_id;type:mediumint unsigned;not null;index:admin_user_admin_role_admin_user_id_index,priority:1;default:0" json:"admin_user_id" db:"admin_user_id"`
	AdminRoleID int64         `gorm:"column:admin_role_id;type:mediumint unsigned;not null;index:admin_user_admin_role_admin_role_id_index,priority:1;default:0" json:"admin_role_id" db:"admin_role_id"`
	CreatedAt   *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt   *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName AdminUserAdminRole's table name
func (*AdminUserAdminRole) TableName() string {
	return TableNameAdminUserAdminRole
}
