// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameAgentUpdateParentLog = "agent_update_parent_logs"

// AgentUpdateParentLog mapped from table <agent_update_parent_logs>
type AgentUpdateParentLog struct {
	ID            int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	AgentName     string        `gorm:"column:agent_name;type:varchar(255);not null;default:'';comment:代理名称" json:"agent_name" db:"agent_name"`               // 代理名称
	AgentID       int64         `gorm:"column:agent_id;type:int;not null;default:0;comment:代理id" json:"agent_id" db:"agent_id"`                               // 代理id
	OldParentName string        `gorm:"column:old_parent_name;type:varchar(255);not null;default:'';comment:旧代理" json:"old_parent_name" db:"old_parent_name"` // 旧代理
	NewParentName string        `gorm:"column:new_parent_name;type:varchar(255);not null;default:'';comment:新代理" json:"new_parent_name" db:"new_parent_name"` // 新代理
	Remark        *string       `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark" db:"remark"`                                                 // 备注
	AdminName     string        `gorm:"column:admin_name;type:varchar(255);not null;default:'';comment:操作管理员" json:"admin_name" db:"admin_name"`              // 操作管理员
	CreatedAt     *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt     *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName AgentUpdateParentLog's table name
func (*AgentUpdateParentLog) TableName() string {
	return TableNameAgentUpdateParentLog
}
