// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameAllowanceAssistanceConfig = "allowance_assistance_config"

// AllowanceAssistanceConfig 助力津贴配置表
type AllowanceAssistanceConfig struct {
	ID                              int64         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id" db:"id"` // 自增id
	Type                            *int64        `gorm:"column:type;type:tinyint unsigned;comment:0:支付层级, 1:vip层级" json:"type" db:"type"`          // 0:支付层级, 1:vip层级
	AllowanceValueVip               *string       `gorm:"column:allowance_value_vip;type:json" json:"allowance_value_vip" db:"allowance_value_vip"`
	AllowanceValuePay               *string       `gorm:"column:allowance_value_pay;type:json;comment:具体津贴值[{'id':10, 'name':'新会员', 'amount':155}, {'id':15, 'name':'老会员', 'amount':200}]" json:"allowance_value_pay" db:"allowance_value_pay"` // 具体津贴值[{'id':10, 'name':'新会员', 'amount':155}, {'id':15, 'name':'老会员', 'amount':200}]
	AllowanceCircle                 *int64        `gorm:"column:allowance_circle;type:int;comment:津贴重置周期(单位:分钟)" json:"allowance_circle" db:"allowance_circle"`                                                                                 // 津贴重置周期(单位:分钟)
	AssistanceCircle                *int64        `gorm:"column:assistance_circle;type:int;comment:助力限制周期(单位:天)" json:"assistance_circle" db:"assistance_circle"`                                                                               // 助力限制周期(单位:天)
	Rule                            *string       `gorm:"column:rule;type:text;comment:津贴活动规则" json:"rule" db:"rule"`                                                                                                                           // 津贴活动规则
	InviteLinkPc                    *string       `gorm:"column:invite_link_pc;type:varchar(255);comment:电脑端邀请链接" json:"invite_link_pc" db:"invite_link_pc"`                                                                                    // 电脑端邀请链接
	InviteLinkMobile                *string       `gorm:"column:invite_link_mobile;type:varchar(255);comment:移动端邀请链接" json:"invite_link_mobile" db:"invite_link_mobile"`                                                                        // 移动端邀请链接
	AllowanceCoverPc                *string       `gorm:"column:allowance_cover_pc;type:varchar(255);comment:电脑端津贴封面图" json:"allowance_cover_pc" db:"allowance_cover_pc"`                                                                       // 电脑端津贴封面图
	AllowanceCoverMobile            *string       `gorm:"column:allowance_cover_mobile;type:varchar(255);comment:移动端津贴封面图" json:"allowance_cover_mobile" db:"allowance_cover_mobile"`                                                           // 移动端津贴封面图
	AllowancePosterPc               *string       `gorm:"column:allowance_poster_pc;type:varchar(255);comment:电脑端津贴海报图" json:"allowance_poster_pc" db:"allowance_poster_pc"`                                                                    // 电脑端津贴海报图
	AllowancePosterMobile           *string       `gorm:"column:allowance_poster_mobile;type:varchar(255);comment:移动端津贴海报图" json:"allowance_poster_mobile" db:"allowance_poster_mobile"`                                                        // 移动端津贴海报图
	AllowanceAssistancePosterPc     *string       `gorm:"column:allowance_assistance_poster_pc;type:varchar(255);comment:电脑端津贴助力海报图" json:"allowance_assistance_poster_pc" db:"allowance_assistance_poster_pc"`                                 // 电脑端津贴助力海报图
	AllowanceAssistancePosterMobile *string       `gorm:"column:allowance_assistance_poster_mobile;type:varchar(255);comment:移动端津贴助力海报图" json:"allowance_assistance_poster_mobile" db:"allowance_assistance_poster_mobile"`                     // 移动端津贴助力海报图
	IsOpen                          *int64        `gorm:"column:is_open;type:tinyint unsigned;index:idx_is_open,priority:1;comment:0:关闭, 1:开启" json:"is_open" db:"is_open"`                                                                     // 0:关闭, 1:开启
	CreatedAt                       *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli;comment:创建时间" json:"created_at" db:"created_at"`                                                                                    // 创建时间
	UpdatedAt                       *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli;comment:更新时间" json:"updated_at" db:"updated_at"`                                                                                    // 更新时间
}

// TableName AllowanceAssistanceConfig's table name
func (*AllowanceAssistanceConfig) TableName() string {
	return TableNameAllowanceAssistanceConfig
}
