// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameBankList = "bank_lists"

// BankList 银行卡列表
type BankList struct {
	ID                  int64         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	ShortName           string        `gorm:"column:short_name;type:varchar(100);not null;uniqueIndex:short_name,priority:1;default:'';comment:银行简称" json:"short_name" db:"short_name"`                 // 银行简称
	BankName            string        `gorm:"column:bank_name;type:varchar(100);not null;default:'';comment:银行名称" json:"bank_name" db:"bank_name"`                                                      // 银行名称
	Sort                *int64        `gorm:"column:sort;type:int;default:999;comment:排序" json:"sort" db:"sort"`                                                                                        // 排序
	BankType            *int64        `gorm:"column:bank_type;type:tinyint;default:1;comment:1:银行卡, 2:数字钱包, 3:易汇钱包, 4:支付宝, 5:微信, 6:数字人民币" json:"bank_type" db:"bank_type"`                              // 1:银行卡, 2:数字钱包, 3:易汇钱包, 4:支付宝, 5:微信, 6:数字人民币
	ImgPath             *string       `gorm:"column:img_path;type:varchar(255);comment:图标路径" json:"img_path" db:"img_path"`                                                                             // 图标路径
	IsOpen              int64         `gorm:"column:is_open;type:tinyint;not null;default:1;comment:是否开启0:否;1:是" json:"is_open" db:"is_open"`                                                           // 是否开启0:否;1:是
	WithdrawType        int64         `gorm:"column:withdraw_type;type:tinyint(1);not null;default:0;comment:1:bank, 2:USDT, 3:购宝, 4:GOPAY" json:"withdraw_type" db:"withdraw_type"`                    // 1:bank, 2:USDT, 3:购宝, 4:GOPAY
	Is3U                int64         `gorm:"column:is_3u;type:tinyint(1);not null;default:0;comment:是否3u,0:否, 1:是" json:"is_3u" db:"is_3u"`                                                            // 是否3u,0:否, 1:是
	VirtualCurrencyName string        `gorm:"column:virtual_currency_name;type:varchar(20);not null;default:'';comment:虚拟货币网络名称, 比如:usdt, btc" json:"virtual_currency_name" db:"virtual_currency_name"` // 虚拟货币网络名称, 比如:usdt, btc
	CreatedAt           *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt           *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	FundsType           int64         `gorm:"column:funds_type;type:tinyint;not null;default:1;comment:资金类型：1 rmb，2 usdt 3钱包" json:"funds_type" db:"funds_type"`           // 资金类型：1 rmb，2 usdt 3钱包
	IsLimitArea         int64         `gorm:"column:is_limit_area;type:tinyint(1);not null;default:0;comment:是否限制地区：1限制，0不限制,默认0" json:"is_limit_area" db:"is_limit_area"` // 是否限制地区：1限制，0不限制,默认0
	LimitAreas          string        `gorm:"column:limit_areas;type:varchar(255);not null;default:'';comment:限制地区，英文逗号相隔" json:"limit_areas" db:"limit_areas"`            // 限制地区，英文逗号相隔
}

// TableName BankList's table name
func (*BankList) TableName() string {
	return TableNameBankList
}
