// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameBindPaySort = "bind_pay_sorts"

// BindPaySort mapped from table <bind_pay_sorts>
type BindPaySort struct {
	ID        int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	PayLevel  string        `gorm:"column:pay_level;type:varchar(255);not null;index:index,priority:1;default:'';comment:pay_level的en_name" json:"pay_level" db:"pay_level"`                    // pay_level的en_name
	BindField string        `gorm:"column:bind_field;type:varchar(255);not null;index:index,priority:2;default:'';comment:关联pay_levels的pc_bind_pay和bind_pay" json:"bind_field" db:"bind_field"` // 关联pay_levels的pc_bind_pay和bind_pay
	PayType   string        `gorm:"column:pay_type;type:varchar(255);not null;index:index,priority:3;default:'';comment:pay_type的en_name" json:"pay_type" db:"pay_type"`                        // pay_type的en_name
	PayID     int64         `gorm:"column:pay_id;type:int unsigned;not null;index:index,priority:4;default:0;comment:pay_id" json:"pay_id" db:"pay_id"`                                         // pay_id
	Sort      int64         `gorm:"column:sort;type:int unsigned;not null;default:0;comment:排序" json:"sort" db:"sort"`                                                                          // 排序
	CreatedAt *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName BindPaySort's table name
func (*BindPaySort) TableName() string {
	return TableNameBindPaySort
}
