// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataIP = "data_ip"

// DataIP mapped from table <data_ip>
type DataIP struct {
	ID                int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id" db:"id"`
	IPStart           *string `gorm:"column:ip_start;type:varchar(15);comment:起始IP" json:"ip_start" db:"ip_start"`                                // 起始IP
	IPEnd             *string `gorm:"column:ip_end;type:varchar(15);comment:结束IP" json:"ip_end" db:"ip_end"`                                      // 结束IP
	NumStart          *int64  `gorm:"column:num_start;type:bigint;index:idx_num_start,priority:1;comment:数字起始IP" json:"num_start" db:"num_start"` // 数字起始IP
	NumEnd            *int64  `gorm:"column:num_end;type:bigint;index:idx_num_end,priority:1;comment:数字结束IP" json:"num_end" db:"num_end"`         // 数字结束IP
	Num               *int64  `gorm:"column:num;type:int;comment:IP数量" json:"num" db:"num"`                                                       // IP数量
	Land              *string `gorm:"column:land;type:varchar(4);comment:大州" json:"land" db:"land"`                                               // 大州
	Region            *string `gorm:"column:region;type:varchar(30);comment:省份" json:"region" db:"region"`                                        // 省份
	City              *string `gorm:"column:city;type:varchar(20);comment:城市" json:"city" db:"city"`                                              // 城市
	Area              *string `gorm:"column:area;type:varchar(20);comment:区县" json:"area" db:"area"`                                              // 区县
	Country           *string `gorm:"column:country;type:varchar(20);comment:国家" json:"country" db:"country"`                                     // 国家
	CountryEnglish    *string `gorm:"column:country_english;type:varchar(50);comment:国家英文" json:"country_english" db:"country_english"`           // 国家英文
	Isp               *string `gorm:"column:isp;type:varchar(40);comment:运营商" json:"isp" db:"isp"`                                                // 运营商
	CountryID         *string `gorm:"column:country_id;type:varchar(10);comment:国家代码" json:"country_id" db:"country_id"`                          // 国家代码
	InternationalCode *string `gorm:"column:international_code;type:varchar(15);comment:国际区号" json:"international_code" db:"international_code"`  // 国际区号
	RegionID          *string `gorm:"column:region_id;type:varchar(20);comment:一级行政代码" json:"region_id" db:"region_id"`                           // 一级行政代码
	CityID            *string `gorm:"column:city_id;type:varchar(20);comment:二级行政代码" json:"city_id" db:"city_id"`                                 // 二级行政代码
	AreaID            *string `gorm:"column:area_id;type:varchar(20);comment:三级行政代码" json:"area_id" db:"area_id"`                                 // 三级行政代码
	Lat               *string `gorm:"column:lat;type:varchar(15);comment:经度" json:"lat" db:"lat"`                                                 // 经度
	Lng               *string `gorm:"column:lng;type:varchar(15);comment:纬度" json:"lng" db:"lng"`                                                 // 纬度
}

// TableName DataIP's table name
func (*DataIP) TableName() string {
	return TableNameDataIP
}
