// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameGiftMoneyLog = "gift_money_logs"

// GiftMoneyLog mapped from table <gift_money_logs>
type GiftMoneyLog struct {
	ID        int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	BatchID   int64         `gorm:"column:batch_id;type:int unsigned;not null;index:gift_money_logs_batch_id_index,priority:1;default:0;comment:批次id" json:"batch_id" db:"batch_id"` // 批次id
	UserID    int64         `gorm:"column:user_id;type:int unsigned;not null;index:gift_money_logs_user_id_index,priority:1;default:0;comment:会员id" json:"user_id" db:"user_id"`     // 会员id
	Status    int64         `gorm:"column:status;type:tinyint unsigned;not null;default:0;comment:是否成功 0:失败 1:成功" json:"status" db:"status"`                                         // 是否成功 0:失败 1:成功
	FailMsg   string        `gorm:"column:fail_msg;type:varchar(2048);not null;default:'';comment:失败原因" json:"fail_msg" db:"fail_msg"`                                               // 失败原因
	CreatedAt *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	Username  *string       `gorm:"column:username;type:varchar(255)" json:"username" db:"username"`
}

// TableName GiftMoneyLog's table name
func (*GiftMoneyLog) TableName() string {
	return TableNameGiftMoneyLog
}
