// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameLiveBroadcastPushUserLog = "live_broadcast_push_user_log"

// LiveBroadcastPushUserLog 直播推送用户日志表
type LiveBroadcastPushUserLog struct {
	ID                  int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	LiveID              *string       `gorm:"column:live_id;type:varchar(255);comment:直播ID" json:"live_id" db:"live_id"`                                                             // 直播ID
	LiveType            int64         `gorm:"column:live_type;type:int;not null;default:0;comment:直播类型" json:"live_type" db:"live_type"`                                             // 直播类型
	UserID              int64         `gorm:"column:user_id;type:bigint;not null;default:0;comment:用户ID" json:"user_id" db:"user_id"`                                                // 用户ID
	EnterTime           *sql.NullTime `gorm:"column:enter_time;type:timestamp;comment:首次进入时间" json:"enter_time" db:"enter_time"`                                                     // 首次进入时间
	LeaveTime           *sql.NullTime `gorm:"column:leave_time;type:timestamp;comment:最后离开时间" json:"leave_time" db:"leave_time"`                                                     // 最后离开时间
	Duration            int64         `gorm:"column:duration;type:bigint;not null;default:0;comment:总持续时长" json:"duration" db:"duration"`                                            // 总持续时长
	UserType            int64         `gorm:"column:user_type;type:tinyint;not null;default:0;comment:用户属性，0=未开户，1=新开户，2=老客户" json:"user_type" db:"user_type"`                       // 用户属性，0=未开户，1=新开户，2=老客户
	FirstRechargeAmount *float64      `gorm:"column:first_recharge_amount;type:decimal(12,4);default:0.0000;comment:开户首存金额" json:"first_recharge_amount" db:"first_recharge_amount"` // 开户首存金额
	TotalDepositAmount  *float64      `gorm:"column:total_deposit_amount;type:decimal(12,4);default:0.0000;comment:总存款金额" json:"total_deposit_amount" db:"total_deposit_amount"`     // 总存款金额
	TotalWithdrawAmount *float64      `gorm:"column:total_withdraw_amount;type:decimal(12,4);default:0.0000;comment:总取款金额" json:"total_withdraw_amount" db:"total_withdraw_amount"`  // 总取款金额
	CreatedAt           *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt           *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName LiveBroadcastPushUserLog's table name
func (*LiveBroadcastPushUserLog) TableName() string {
	return TableNameLiveBroadcastPushUserLog
}
