// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameLotteryConfig = "lottery_config"

// LotteryConfig 大转盘配置表
type LotteryConfig struct {
	ID              int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	ActivityID      int64         `gorm:"column:activity_id;type:int;not null;uniqueIndex:lottery_config_activity_id_unique,priority:1;default:0;comment:活动ID" json:"activity_id" db:"activity_id"` // 活动ID
	ProbabilityType int64         `gorm:"column:probability_type;type:tinyint;not null;default:0;comment:概率类型，0固定概率，1浮动概率" json:"probability_type" db:"probability_type"`                           // 概率类型，0固定概率，1浮动概率
	OperatorName    string        `gorm:"column:operator_name;type:varchar(100);not null;default:'';comment:操作人" json:"operator_name" db:"operator_name"`                                           // 操作人
	PlayName        string        `gorm:"column:play_name;type:varchar(100);not null;default:'';comment:玩法名称" json:"play_name" db:"play_name"`                                                      // 玩法名称
	Persons         int64         `gorm:"column:persons;type:int;not null;default:-1;comment:可参与人数，默认-1 不限制" json:"persons" db:"persons"`                                                           // 可参与人数，默认-1 不限制
	Chance          int64         `gorm:"column:chance;type:int;not null;default:-1;comment:人均抽奖次数，默认-1 不限制" json:"chance" db:"chance"`                                                             // 人均抽奖次数，默认-1 不限制
	Status          int64         `gorm:"column:status;type:tinyint;not null;default:0;comment:状态; 0无效 1有效" json:"status" db:"status"`                                                              // 状态; 0无效 1有效
	CreatedAt       *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt       *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	StartAt         *sql.NullTime `gorm:"column:start_at;type:timestamp;comment:开始时间" json:"start_at" db:"start_at"` // 开始时间
	EndAt           *sql.NullTime `gorm:"column:end_at;type:timestamp;comment:结束时间" json:"end_at" db:"end_at"`       // 结束时间
}

// TableName LotteryConfig's table name
func (*LotteryConfig) TableName() string {
	return TableNameLotteryConfig
}
