// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID           int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	Title        string        `gorm:"column:title;type:varchar(255);not null;default:'';comment:消息标题" json:"title" db:"title"`                                                                                         // 消息标题
	Content      *string       `gorm:"column:content;type:text;comment:消息内容" json:"content" db:"content"`                                                                                                               // 消息内容
	MsgID        int64         `gorm:"column:msg_id;type:tinyint unsigned;not null;index:idx_messages_main_index,priority:1;index:messages_msg_id_index,priority:1;default:0;comment:消息类型id" json:"msg_id" db:"msg_id"` // 消息类型id
	MsgName      string        `gorm:"column:msg_name;type:varchar(255);not null;default:'';comment:消息类型标题" json:"msg_name" db:"msg_name"`                                                                              // 消息类型标题
	FromUserid   *int64        `gorm:"column:from_userid;type:int unsigned;comment:发送者用户id" json:"from_userid" db:"from_userid"`                                                                                        // 发送者用户id
	FromUsername *string       `gorm:"column:from_username;type:varchar(255);index:messages_from_username_index,priority:1;comment:发件人" json:"from_username" db:"from_username"`                                        // 发件人
	UserID       *int64        `gorm:"column:user_id;type:int unsigned;index:idx_messages_main_index,priority:3;comment:收件用户id" json:"user_id" db:"user_id"`                                                            // 收件用户id
	Username     *string       `gorm:"column:username;type:varchar(255);index:messages_to_username_index,priority:1;comment:收件人" json:"username" db:"username"`                                                         // 收件人
	IsRead       int64         `gorm:"column:is_read;type:tinyint(1);not null;default:0;comment:0未读，1已读" json:"is_read" db:"is_read"`                                                                                   // 0未读，1已读
	IsWelcome    *int64        `gorm:"column:is_welcome;type:tinyint;index:idx_is_welcome,priority:1;comment:是否欢迎消息 0:不是;1:是" json:"is_welcome" db:"is_welcome"`                                                        // 是否欢迎消息 0:不是;1:是
	IsTop        int64         `gorm:"column:is_top;type:tinyint(1);not null;default:0;comment:是否置顶0:否;1:是" json:"is_top" db:"is_top"`                                                                                  // 是否置顶0:否;1:是
	IsOpen       int64         `gorm:"column:is_open;type:tinyint(1);not null;index:idx_messages_main_index,priority:4;default:1;comment:是否开启0:否;1:是" json:"is_open" db:"is_open"`                                      // 是否开启0:否;1:是
	IsSolved     *int64        `gorm:"column:is_solved;type:tinyint;comment:是否解决0:未解决;1:解决" json:"is_solved" db:"is_solved"`                                                                                            // 是否解决0:未解决;1:解决
	AppPlat      *int64        `gorm:"column:app_plat;type:tinyint(1);default:1;comment:平台类型 1综合 2体育" json:"app_plat" db:"app_plat"`                                                                                    // 平台类型 1综合 2体育
	AdminName    *string       `gorm:"column:admin_name;type:varchar(255);comment:添加消息的后台管理员" json:"admin_name" db:"admin_name"`                                                                                        // 添加消息的后台管理员
	CreatedAt    *sql.NullTime `gorm:"column:created_at;type:bigint;index:idx_messages_main_index,priority:2;default:CURRENT_TIMESTAMP;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt    *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	ReadiedAt    *sql.NullTime `gorm:"column:readied_at;type:timestamp;comment:私信管理员阅读时间" json:"readied_at" db:"readied_at"`        // 私信管理员阅读时间
	Sort         int64         `gorm:"column:sort;type:int;not null;default:0;comment:权重" json:"sort" db:"sort"`                    // 权重
	PayLevels    *string       `gorm:"column:pay_levels;type:varchar(256);comment:指定层级（逗号分隔)" json:"pay_levels" db:"pay_levels"`    // 指定层级（逗号分隔)
	AgentNames   *string       `gorm:"column:agent_names;type:varchar(256);comment:指定代理（逗号分隔）" json:"agent_names" db:"agent_names"` // 指定代理（逗号分隔）
	MsgType      *int64        `gorm:"column:msg_type;type:tinyint;comment:消息主体类型 0文本 1图片 2视频" json:"msg_type" db:"msg_type"`       // 消息主体类型 0文本 1图片 2视频
	Path         *string       `gorm:"column:path;type:json;comment:图片、视频地址" json:"path" db:"path"`                                 // 图片、视频地址
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
