// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameOnlinePay = "online_pays"

// OnlinePay mapped from table <online_pays>
type OnlinePay struct {
	ID                 int64         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	PayCode            string        `gorm:"column:pay_code;type:varchar(100);not null;default:'';comment:支付英文名" json:"pay_code" db:"pay_code"`               // 支付英文名
	PayName            string        `gorm:"column:pay_name;type:varchar(100);not null;default:'';comment:支付英中文名" json:"pay_name" db:"pay_name"`              // 支付英中文名
	PayType            string        `gorm:"column:pay_type;type:varchar(100);not null;default:'';comment:pay_types表中的en_name" json:"pay_type" db:"pay_type"` // pay_types表中的en_name
	Account            string        `gorm:"column:account;type:varchar(255);not null;default:'';comment:商户号" json:"account" db:"account"`                    // 商户号
	MerchantKey        string        `gorm:"column:merchant_key;type:varchar(255);not null;default:'';comment:商户密匙" json:"merchant_key" db:"merchant_key"`    // 商户密匙
	ChannelCode        string        `gorm:"column:channel_code;type:varchar(50);not null;default:'';comment:通道编码" json:"channel_code" db:"channel_code"`     // 通道编码
	Gateway            string        `gorm:"column:gateway;type:varchar(255);not null;default:'';comment:第三方网关地址" json:"gateway" db:"gateway"`                // 第三方网关地址
	PayURL             string        `gorm:"column:pay_url;type:varchar(255);not null;default:'';comment:支付地址" json:"pay_url" db:"pay_url"`                   // 支付地址
	MinMoney           *float64      `gorm:"column:min_money;type:decimal(12,2);comment:支付最小金额" json:"min_money" db:"min_money"`                              // 支付最小金额
	MaxMoney           *float64      `gorm:"column:max_money;type:decimal(12,2);comment:支付最大金额" json:"max_money" db:"max_money"`                              // 支付最大金额
	PayLevel           *string       `gorm:"column:pay_level;type:varchar(255);comment:支付类别 多个以逗号分隔" json:"pay_level" db:"pay_level"`                         // 支付类别 多个以逗号分隔
	IP                 *string       `gorm:"column:ip;type:varchar(255);comment:第三方ip" json:"ip" db:"ip"`                                                     // 第三方ip
	Sort               *int64        `gorm:"column:sort;type:int;comment:排序" json:"sort" db:"sort"`                                                           // 排序
	Platform           *string       `gorm:"column:platform;type:varchar(255);default:1,4;comment:支付开放的支付平台,1:手机端;4:pc端" json:"platform" db:"platform"`       // 支付开放的支付平台,1:手机端;4:pc端
	IsSaoma            *int64        `gorm:"column:is_saoma;type:tinyint;comment:0:否 1:扫码" json:"is_saoma" db:"is_saoma"`                                     // 0:否 1:扫码
	IsDaifu            *int64        `gorm:"column:is_daifu;type:tinyint;comment:是否是代付0:否；1：是" json:"is_daifu" db:"is_daifu"`                                 // 是否是代付0:否；1：是
	IsZhuanka          *int64        `gorm:"column:is_zhuanka;type:tinyint;comment:是否是转卡三方" json:"is_zhuanka" db:"is_zhuanka"`                                // 是否是转卡三方
	IsRange            *int64        `gorm:"column:is_range;type:tinyint;default:1;comment:是否是固定金额0:是；1：否;0:代表固定金额" json:"is_range" db:"is_range"`            // 是否是固定金额0:是；1：否;0:代表固定金额
	BankType           *int64        `gorm:"column:bank_type;type:tinyint;default:1;comment:1:银行卡, 2:数字钱包" json:"bank_type" db:"bank_type"`                   // 1:银行卡, 2:数字钱包
	ExRate             *float64      `gorm:"column:ex_rate;type:decimal(7,2);default:1.00;comment:汇率" json:"ex_rate" db:"ex_rate"`                            // 汇率
	QuickAmount        *string       `gorm:"column:quick_amount;type:varchar(255);comment:存款金额:多个值,则用逗号隔开" json:"quick_amount" db:"quick_amount"`             // 存款金额:多个值,则用逗号隔开
	Remark             *string       `gorm:"column:remark;type:varchar(255);comment:前台的支付提示" json:"remark" db:"remark"`                                       // 前台的支付提示
	Extra              *string       `gorm:"column:extra;type:varchar(255);comment:备用字段" json:"extra" db:"extra"`                                             // 备用字段
	AdminUser          *string       `gorm:"column:admin_user;type:varchar(255);comment:编辑者" json:"admin_user" db:"admin_user"`                               // 编辑者
	BetAmountRate      *int64        `gorm:"column:bet_amount_rate;type:int unsigned;default:1;comment:打码量倍数" json:"bet_amount_rate" db:"bet_amount_rate"`    // 打码量倍数
	IsOpen             *int64        `gorm:"column:is_open;type:tinyint;default:1;comment:是否开启0:否;1:是" json:"is_open" db:"is_open"`                           // 是否开启0:否;1:是
	IsThird            *int64        `gorm:"column:is_third;type:tinyint;default:1;comment:是否是第三方支付0:否；1：是" json:"is_third" db:"is_third"`                    // 是否是第三方支付0:否；1：是
	CreatedAt          *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt          *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	DailyMaxMoney      *float64      `gorm:"column:daily_max_money;type:decimal(12,2);comment:单日最大额度" json:"daily_max_money" db:"daily_max_money"`                      // 单日最大额度
	GiftMoneyRate      *float64      `gorm:"column:gift_money_rate;type:decimal(4,3);default:0.000;comment:优惠比例" json:"gift_money_rate" db:"gift_money_rate"`           // 优惠比例
	BoRemark           string        `gorm:"column:bo_remark;type:varchar(255);not null;default:'';comment:备注" json:"bo_remark" db:"bo_remark"`                         // 备注
	PcIsRange          int64         `gorm:"column:pc_is_range;type:tinyint;not null;default:0;comment:电脑是否是固定金额0:是；1：否" json:"pc_is_range" db:"pc_is_range"`           // 电脑是否是固定金额0:是；1：否
	PcQuickAmount      *string       `gorm:"column:pc_quick_amount;type:varchar(255);comment:电脑存款金额:多个值,则用逗号隔开" json:"pc_quick_amount" db:"pc_quick_amount"`            // 电脑存款金额:多个值,则用逗号隔开
	IPList             *string       `gorm:"column:ip_list;type:json;comment:IP过滤列表" json:"ip_list" db:"ip_list"`                                                       // IP过滤列表
	IsMatchFastPay     *int64        `gorm:"column:is_match_fast_pay;type:tinyint;comment:是否开启极速充值匹配0:禁用;1:开启" json:"is_match_fast_pay" db:"is_match_fast_pay"`         // 是否开启极速充值匹配0:禁用;1:开启
	ChannelName        *string       `gorm:"column:channel_name;type:varchar(50);comment:通道名称" json:"channel_name" db:"channel_name"`                                   // 通道名称
	RecommendedChannel *string       `gorm:"column:recommended_channel;type:json;comment:推荐通道" json:"recommended_channel" db:"recommended_channel"`                     // 推荐通道
	LastPayType        int64         `gorm:"column:last_pay_type;type:tinyint unsigned;not null;default:0;comment:兜底支付类型 1：极速" json:"last_pay_type" db:"last_pay_type"` // 兜底支付类型 1：极速
}

// TableName OnlinePay's table name
func (*OnlinePay) TableName() string {
	return TableNameOnlinePay
}
