// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNamePushUserMessageAd = "push_user_message_ads"

// PushUserMessageAd 推送广告配置表
type PushUserMessageAd struct {
	ID                   int64         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	Title                string        `gorm:"column:title;type:varchar(255);not null;default:'';comment:广告标题" json:"title" db:"title"`                                                                                                    // 广告标题
	Type                 int64         `gorm:"column:type;type:tinyint unsigned;not null;default:0;comment:广告类型 1:弹窗 2:悬浮" json:"type" db:"type"`                                                                                          // 广告类型 1:弹窗 2:悬浮
	Pos                  int64         `gorm:"column:pos;type:tinyint unsigned;not null;index:ads_pos_index,priority:1;default:0;comment:广告位置 1:首页 2:充值 3:取款 4:优惠中心 5:会员中心" json:"pos" db:"pos"`                                           // 广告位置 1:首页 2:充值 3:取款 4:优惠中心 5:会员中心
	Plat                 string        `gorm:"column:plat;type:varchar(255);not null;index:ads_plat_index,priority:1;default:'';comment:终端（同user表的plat）, 逗号分割" json:"plat" db:"plat"`                                                      // 终端（同user表的plat）, 逗号分割
	Freq                 int64         `gorm:"column:freq;type:tinyint unsigned;not null;default:0;comment:频次 1:每次登陆 2:每天一次 3:只弹一次" json:"freq" db:"freq"`                                                                                 // 频次 1:每次登陆 2:每天一次 3:只弹一次
	PcImgPath            string        `gorm:"column:pc_img_path;type:varchar(1024);not null;default:'';comment:pc端图片" json:"pc_img_path" db:"pc_img_path"`                                                                                // pc端图片
	MobileImgPath        string        `gorm:"column:mobile_img_path;type:varchar(1024);not null;default:'';comment:mobile端图片" json:"mobile_img_path" db:"mobile_img_path"`                                                                // mobile端图片
	PcJumpURL            string        `gorm:"column:pc_jump_url;type:varchar(1024);not null;default:'';comment:pc跳转地址" json:"pc_jump_url" db:"pc_jump_url"`                                                                               // pc跳转地址
	H5JumpURL            string        `gorm:"column:h5_jump_url;type:varchar(1024);not null;default:'';comment:h5跳转地址" json:"h5_jump_url" db:"h5_jump_url"`                                                                               // h5跳转地址
	IosJumpURL           string        `gorm:"column:ios_jump_url;type:varchar(1024);not null;default:'';comment:ios跳转地址" json:"ios_jump_url" db:"ios_jump_url"`                                                                           // ios跳转地址
	AndroidJumpURL       string        `gorm:"column:android_jump_url;type:varchar(1024);not null;default:'';comment:android跳转地址" json:"android_jump_url" db:"android_jump_url"`                                                           // android跳转地址
	UserType             int64         `gorm:"column:user_type;type:tinyint unsigned;not null;index:ads_user_type_index,priority:1;default:1;comment:用户群类型 1:所有用户 2:指定用户 3:指定VIP层级 4:指定支付层级 5:指定VIP+支付层级" json:"user_type" db:"user_type"` // 用户群类型 1:所有用户 2:指定用户 3:指定VIP层级 4:指定支付层级 5:指定VIP+支付层级
	UserList             *string       `gorm:"column:user_list;type:longtext;comment:用户群，多个用户用逗号分割" json:"user_list" db:"user_list"`                                                                                                       // 用户群，多个用户用逗号分割
	UserLevels           string        `gorm:"column:user_levels;type:varchar(2048);not null;default:'';comment:user_level的id,逗号分割" json:"user_levels" db:"user_levels"`                                                                   // user_level的id,逗号分割
	PayLevels            string        `gorm:"column:pay_levels;type:varchar(2048);not null;default:'';comment:pay_level的en_name,逗号分割" json:"pay_levels" db:"pay_levels"`                                                                  // pay_level的en_name,逗号分割
	Sort                 int64         `gorm:"column:sort;type:int unsigned;not null;index:ads_sort_index,priority:1;default:0;comment:排序" json:"sort" db:"sort"`                                                                          // 排序
	IsOpen               int64         `gorm:"column:is_open;type:tinyint(1);not null;default:0;comment:状态" json:"is_open" db:"is_open"`                                                                                                   // 状态
	IsDel                int64         `gorm:"column:is_del;type:tinyint(1);not null;default:0;comment:是否删除" json:"is_del" db:"is_del"`                                                                                                    // 是否删除
	Remark               string        `gorm:"column:remark;type:varchar(255);not null;default:'';comment:备注" json:"remark" db:"remark"`                                                                                                   // 备注
	AdminName            string        `gorm:"column:admin_name;type:varchar(255);not null;default:'';comment:操作人员" json:"admin_name" db:"admin_name"`                                                                                     // 操作人员
	CreatedAt            *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt            *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	JumpMethod           int64         `gorm:"column:jump_method;type:tinyint(1);not null;default:1;comment:跳转方式 1 链接 2打开私信详情" json:"jump_method" db:"jump_method"`                       // 跳转方式 1 链接 2打开私信详情
	IsFromNewPushMessage *int64        `gorm:"column:is_from_new_push_message;type:tinyint;default:1;comment:是否来自新的推送私信消息" json:"is_from_new_push_message" db:"is_from_new_push_message"` // 是否来自新的推送私信消息
}

// TableName PushUserMessageAd's table name
func (*PushUserMessageAd) TableName() string {
	return TableNamePushUserMessageAd
}
