// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameRedpacketPlayNum = "redpacket_play_num"

// RedpacketPlayNum 充值金额对应抽红包次数
type RedpacketPlayNum struct {
	ID             int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	Type           int64         `gorm:"column:type;type:tinyint;not null;default:0;comment:状态; 0:红包, 1:大转盘" json:"type" db:"type"`                                                                               // 状态; 0:红包, 1:大转盘
	RechargeAmount float64       `gorm:"column:recharge_amount;type:decimal(11,2);not null;index:idx_recharge_amount_status,priority:1;default:0.00;comment:充值金额(元)" json:"recharge_amount" db:"recharge_amount"` // 充值金额(元)
	Num            int64         `gorm:"column:num;type:int;not null;default:0;comment:抽取次数" json:"num" db:"num"`                                                                                                 // 抽取次数
	Status         int64         `gorm:"column:status;type:tinyint;not null;index:idx_recharge_amount_status,priority:2;default:0;comment:状态; 0:隐藏, 1:正常" json:"status" db:"status"`                              // 状态; 0:隐藏, 1:正常
	OperatorID     int64         `gorm:"column:operator_id;type:int;not null;default:0;comment:操作人id" json:"operator_id" db:"operator_id"`                                                                        // 操作人id
	OperatorName   string        `gorm:"column:operator_name;type:varchar(50);not null;default:'';comment:操作人姓名" json:"operator_name" db:"operator_name"`                                                         // 操作人姓名
	CreatedAt      *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt      *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName RedpacketPlayNum's table name
func (*RedpacketPlayNum) TableName() string {
	return TableNameRedpacketPlayNum
}
