// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameRiskGameBlacklist = "risk_game_blacklists"

// RiskGameBlacklist 游戏黑名单表
type RiskGameBlacklist struct {
	ID             int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	SeriesID       int64         `gorm:"column:series_id;type:smallint unsigned;not null;default:0;comment:系列id" json:"series_id" db:"series_id"`                                                     // 系列id
	SeriesName     string        `gorm:"column:series_name;type:varchar(255);not null;default:'';comment:系列名称" json:"series_name" db:"series_name"`                                                   // 系列名称
	GameCode       string        `gorm:"column:game_code;type:varchar(255);not null;index:risk_game_blacklists_game_code_index,priority:1;default:'';comment:游戏code" json:"game_code" db:"game_code"` // 游戏code
	SeriesGameName string        `gorm:"column:series_game_name;type:varchar(255);not null;default:'';comment:场馆名称" json:"series_game_name" db:"series_game_name"`                                    // 场馆名称
	GameID         string        `gorm:"column:game_id;type:varchar(255);not null;index:risk_game_blacklists_game_id_index,priority:1;default:'';comment:游戏id" json:"game_id" db:"game_id"`           // 游戏id
	GameGame       string        `gorm:"column:game_game;type:varchar(255);not null;default:'';comment:游戏名称" json:"game_game" db:"game_game"`                                                         // 游戏名称
	Remark         *string       `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark" db:"remark"`                                                                                        // 备注
	AdminID        int64         `gorm:"column:admin_id;type:int unsigned;not null;default:0;comment:管理员id" json:"admin_id" db:"admin_id"`                                                            // 管理员id
	AdminName      string        `gorm:"column:admin_name;type:varchar(255);not null;default:'';comment:管理员名称" json:"admin_name" db:"admin_name"`                                                     // 管理员名称
	CreatedAt      *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt      *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName RiskGameBlacklist's table name
func (*RiskGameBlacklist) TableName() string {
	return TableNameRiskGameBlacklist
}
