// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameSeriesGame = "series_games"

// SeriesGame mapped from table <series_games>
type SeriesGame struct {
	ID            int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	SeriesID      int64         `gorm:"column:series_id;type:smallint unsigned;not null;index:series_games_series_id_index,priority:1;default:0" json:"series_id" db:"series_id"`
	CnName        string        `gorm:"column:cn_name;type:varchar(255);not null;default:''" json:"cn_name" db:"cn_name"`
	GameCode      string        `gorm:"column:game_code;type:varchar(255);not null;uniqueIndex:series_games_game_code_unique,priority:1;default:''" json:"game_code" db:"game_code"`
	IsTest        int64         `gorm:"column:is_test;type:tinyint(1);not null;default:0;comment:是否在测试:0:正式；1:只有测试人员能玩" json:"is_test" db:"is_test"` // 是否在测试:0:正式；1:只有测试人员能玩
	IsOpen        int64         `gorm:"column:is_open;type:tinyint(1);not null;default:1;comment:是否开放" json:"is_open" db:"is_open"`                  // 是否开放
	PicURL        string        `gorm:"column:pic_url;type:varchar(255);not null;default:'';comment:图标地址" json:"pic_url" db:"pic_url"`               // 图标地址
	HotPicURL     *string       `gorm:"column:hot_pic_url;type:varchar(255);comment:热门图片地址" json:"hot_pic_url" db:"hot_pic_url"`                     // 热门图片地址
	Sort          int64         `gorm:"column:sort;type:smallint unsigned;not null;default:0;comment:排序" json:"sort" db:"sort"`                      // 排序
	HotSort       int64         `gorm:"column:hot_sort;type:smallint unsigned;not null;default:0;comment:热门排序" json:"hot_sort" db:"hot_sort"`        // 热门排序
	StartAt       *sql.NullTime `gorm:"column:start_at;type:datetime;comment:休市开始日期" json:"start_at" db:"start_at"`                                  // 休市开始日期
	EndAt         *sql.NullTime `gorm:"column:end_at;type:datetime;comment:休市结束日期,结束日期即为开始日期" json:"end_at" db:"end_at"`                             // 休市结束日期,结束日期即为开始日期
	MinMoney      float64       `gorm:"column:min_money;type:decimal(10,2);not null;default:0.00;comment:最小金额" json:"min_money" db:"min_money"`      // 最小金额
	MaxMoney      float64       `gorm:"column:max_money;type:decimal(10,2);not null;default:0.00;comment:投注时最大金额" json:"max_money" db:"max_money"`   // 投注时最大金额
	IsHot         *int64        `gorm:"column:is_hot;type:tinyint;comment:是否热门0:否；1:是" json:"is_hot" db:"is_hot"`                                    // 是否热门0:否；1:是
	IsShow        *int64        `gorm:"column:is_show;type:tinyint;default:1;comment:是否有二级页面0:否；1:是" json:"is_show" db:"is_show"`                    // 是否有二级页面0:否；1:是
	Fanshui       *float64      `gorm:"column:fanshui;type:decimal(5,2);default:0.00;comment:返水百分比%" json:"fanshui" db:"fanshui"`                    // 返水百分比%
	Remark        *string       `gorm:"column:remark;type:varchar(255);comment:手机端备注" json:"remark" db:"remark"`                                     // 手机端备注
	GameInfo      *string       `gorm:"column:game_info;type:text;comment:pc端游戏说明" json:"game_info" db:"game_info"`                                  // pc端游戏说明
	CreatedAt     *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt     *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	GameRecordURL string        `gorm:"column:game_record_url;type:varchar(255);not null;default:'';comment:游戏记录地址" json:"game_record_url" db:"game_record_url"` // 游戏记录地址
	WorldURL      string        `gorm:"column:world_url;type:varchar(255);not null;default:'';comment:世界杯图片" json:"world_url" db:"world_url"`                    // 世界杯图片
	AdminID       int64         `gorm:"column:admin_id;type:int;not null;default:0" json:"admin_id" db:"admin_id"`
	AdminName     string        `gorm:"column:admin_name;type:varchar(255);not null;default:''" json:"admin_name" db:"admin_name"`
}

// TableName SeriesGame's table name
func (*SeriesGame) TableName() string {
	return TableNameSeriesGame
}
