// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameUserBindThirdWallet = "user_bind_third_wallet"

// UserBindThirdWallet 用户绑定的第三方钱包信息
type UserBindThirdWallet struct {
	ID          int64         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	UserID      int64         `gorm:"column:user_id;type:int;not null;index:user_id_third_type_wallet_id_index,priority:1;default:0;comment:用户ID" json:"user_id" db:"user_id"`                   // 用户ID
	ThirdType   int64         `gorm:"column:third_type;type:tinyint;not null;index:user_id_third_type_wallet_id_index,priority:2;default:0;comment:三方类型:1:购宝" json:"third_type" db:"third_type"` // 三方类型:1:购宝
	ShortName   string        `gorm:"column:short_name;type:varchar(50);not null;default:'';comment:银行简称" json:"short_name" db:"short_name"`                                                     // 银行简称
	BankName    string        `gorm:"column:bank_name;type:varchar(50);not null;default:'';comment:银行卡姓名" json:"bank_name" db:"bank_name"`                                                       // 银行卡姓名
	WalletID    string        `gorm:"column:wallet_id;type:varchar(80);not null;index:user_id_third_type_wallet_id_index,priority:3;default:'';comment:用户钱包ID" json:"wallet_id" db:"wallet_id"`  // 用户钱包ID
	Balance     *float64      `gorm:"column:balance;type:decimal(12,4);default:0.0000;comment:钱包余额" json:"balance" db:"balance"`                                                                 // 钱包余额
	Username    *string       `gorm:"column:username;type:varchar(50);comment:钱包用户名" json:"username" db:"username"`                                                                              // 钱包用户名
	Nickname    *string       `gorm:"column:nickname;type:varchar(50);comment:钱包昵称" json:"nickname" db:"nickname"`                                                                               // 钱包昵称
	AccessToken *string       `gorm:"column:access_token;type:varchar(100);comment:钱包授权访问access_token" json:"access_token" db:"access_token"`                                                    // 钱包授权访问access_token
	Remark      string        `gorm:"column:remark;type:varchar(100);not null;default:'';comment:备注" json:"remark" db:"remark"`                                                                  // 备注
	IsOpen      *int64        `gorm:"column:is_open;type:tinyint;default:1;comment:是否开启 0:否;1:是" json:"is_open" db:"is_open"`                                                                    // 是否开启 0:否;1:是
	CreatedAt   *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt   *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName UserBindThirdWallet's table name
func (*UserBindThirdWallet) TableName() string {
	return TableNameUserBindThirdWallet
}
