// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameUserBlacklist = "user_blacklists"

// UserBlacklist mapped from table <user_blacklists>
type UserBlacklist struct {
	ID          int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	UserID      int64         `gorm:"column:user_id;type:int unsigned;not null;index:user_blacklists_user_id_index,priority:1;default:0;comment:会员id" json:"user_id" db:"user_id"`      // 会员id
	Username    string        `gorm:"column:username;type:varchar(255);not null;index:user_blacklists_username_index,priority:1;default:'';comment:会员名称" json:"username" db:"username"` // 会员名称
	LoginParams *string       `gorm:"column:login_params;type:varchar(600);comment:登陆参数" json:"login_params" db:"login_params"`                                                         // 登陆参数
	Domain      *string       `gorm:"column:domain;type:varchar(255);comment:网站域名" json:"domain" db:"domain"`                                                                           // 网站域名
	IP          string        `gorm:"column:ip;type:varchar(255);not null;default:'';comment:ip" json:"ip" db:"ip"`                                                                     // ip
	IPArea      string        `gorm:"column:ip_area;type:varchar(255);not null;default:'';comment:区域" json:"ip_area" db:"ip_area"`                                                      // 区域
	IsDeleted   int64         `gorm:"column:is_deleted;type:tinyint(1);not null;default:0;comment:是否删除" json:"is_deleted" db:"is_deleted"`                                              // 是否删除
	AdminName   *string       `gorm:"column:admin_name;type:varchar(255);comment:操作管理员" json:"admin_name" db:"admin_name"`                                                              // 操作管理员
	Plat        *int64        `gorm:"column:plat;type:tinyint;comment:终端;1:h5;2:android;3:ios;4:pc" json:"plat" db:"plat"`                                                              // 终端;1:h5;2:android;3:ios;4:pc
	AppPlat     *int64        `gorm:"column:app_plat;type:tinyint(1);default:1;comment:平台 1:综合 2:体育" json:"app_plat" db:"app_plat"`                                                     // 平台 1:综合 2:体育
	CreatedAt   *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt   *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName UserBlacklist's table name
func (*UserBlacklist) TableName() string {
	return TableNameUserBlacklist
}
