// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameUserEngagelabRegisterIdsCopy1 = "user_engagelab_register_ids_copy1"

// UserEngagelabRegisterIdsCopy1 mapped from table <user_engagelab_register_ids_copy1>
type UserEngagelabRegisterIdsCopy1 struct {
	ID             int64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	UserID         int64         `gorm:"column:user_id;type:bigint unsigned;not null;index:user_engagelab_register_ids_user_id_index,priority:1;default:0" json:"user_id" db:"user_id"`
	Username       string        `gorm:"column:username;type:varchar(255);not null;uniqueIndex:user_engagelab_register_ids_username_plat_unique,priority:1;index:user_engagelab_register_ids_username_index,priority:1;default:''" json:"username" db:"username"`
	Plat           int64         `gorm:"column:plat;type:tinyint unsigned;not null;uniqueIndex:user_engagelab_register_ids_username_plat_unique,priority:2;index:user_engagelab_register_ids_plat_index,priority:1;default:0;comment:终端设备" json:"plat" db:"plat"` // 终端设备
	RegistrationID string        `gorm:"column:registration_id;type:varchar(255);not null;default:'';comment:注册id" json:"registration_id" db:"registration_id"`                                                                                                   // 注册id
	CreatedAt      *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt      *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
	Host           string        `gorm:"column:host;type:varchar(255);not null;default:'';comment:域名" json:"host" db:"host"` // 域名
}

// TableName UserEngagelabRegisterIdsCopy1's table name
func (*UserEngagelabRegisterIdsCopy1) TableName() string {
	return TableNameUserEngagelabRegisterIdsCopy1
}
