// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameUserRiskRemoveRecord = "user_risk_remove_record"

// UserRiskRemoveRecord 移出风险名单记录表
type UserRiskRemoveRecord struct {
	ID           int64         `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id" db:"id"`
	UserID       *int64        `gorm:"column:user_id;type:int;index:user_risk_list_user_id_index,priority:1;comment:用户uid" json:"user_id" db:"user_id"`            // 用户uid
	Username     *string       `gorm:"column:username;type:varchar(50);index:user_risk_list_username_index,priority:1;comment:用户账号" json:"username" db:"username"` // 用户账号
	JoinedAt     *sql.NullTime `gorm:"column:joined_at;type:timestamp;comment:移入风险名单时间" json:"joined_at" db:"joined_at"`                                           // 移入风险名单时间
	RemovedAt    *sql.NullTime `gorm:"column:removed_at;type:timestamp;comment:移出风险名单时间" json:"removed_at" db:"removed_at"`                                        // 移出风险名单时间
	AddAdminName *[]byte       `gorm:"column:add_admin_name;type:varbinary(50);comment:风险添加人" json:"add_admin_name" db:"add_admin_name"`                           // 风险添加人
	AdminName    *string       `gorm:"column:admin_name;type:varchar(50);comment:操作人" json:"admin_name" db:"admin_name"`                                           // 操作人
	CreatedAt    *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt    *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName UserRiskRemoveRecord's table name
func (*UserRiskRemoveRecord) TableName() string {
	return TableNameUserRiskRemoveRecord
}
