// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "database/sql"

const TableNameUserGameBetAmountsCopy = "user_game_bet_amounts_copy"

// UserGameBetAmountsCopy 游戏打码量表
type UserGameBetAmountsCopy struct {
	ID             int64         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id" db:"id"`
	DateAt         *string       `gorm:"column:date_at;type:varchar(50);index:adx_date_game_user_fanshui,priority:1;index:adx_yongjin_date,priority:2;index:date_at,priority:1;comment:当天时间" json:"date_at" db:"date_at"`                              // 当天时间
	SeriesID       int64         `gorm:"column:series_id;type:int;not null;default:0;comment:游戏系列id" json:"series_id" db:"series_id"`                                                                                                                  // 游戏系列id
	GameCode       string        `gorm:"column:game_code;type:varchar(50);not null;index:adx_date_game_user_fanshui,priority:2;index:game_code_index,priority:1;default:'';comment:游戏类型" json:"game_code" db:"game_code"`                              // 游戏类型
	UserID         int64         `gorm:"column:user_id;type:int;not null;index:adx_date_game_user_fanshui,priority:3;index:user_game_bet_amounts_user_id_index,priority:1;default:0;comment:用户id" json:"user_id" db:"user_id"`                         // 用户id
	Username       string        `gorm:"column:username;type:varchar(100);not null;default:'';comment:用户名" json:"username" db:"username"`                                                                                                              // 用户名
	ParentID       int64         `gorm:"column:parent_id;type:int;not null;default:0;comment:用户id" json:"parent_id" db:"parent_id"`                                                                                                                    // 用户id
	ParentName     string        `gorm:"column:parent_name;type:varchar(100);not null;default:'';comment:用户名" json:"parent_name" db:"parent_name"`                                                                                                     // 用户名
	ForefatherIds  *string       `gorm:"column:forefather_ids;type:varchar(255);comment:上级树,多个以逗号隔开" json:"forefather_ids" db:"forefather_ids"`                                                                                                        // 上级树,多个以逗号隔开
	BetNums        int64         `gorm:"column:bet_nums;type:int;not null;default:0;comment:注单量" json:"bet_nums" db:"bet_nums"`                                                                                                                        // 注单量
	BetAmount      *float64      `gorm:"column:bet_amount;type:decimal(10,2);default:0.00;comment:用户投注金额 包括无效金额" json:"bet_amount" db:"bet_amount"`                                                                                                    // 用户投注金额 包括无效金额
	ValidBetAmount float64       `gorm:"column:valid_bet_amount;type:decimal(12,2);not null;default:0.00;comment:有效投注金额" json:"valid_bet_amount" db:"valid_bet_amount"`                                                                                // 有效投注金额
	NetAmount      float64       `gorm:"column:net_amount;type:decimal(12,2);not null;default:0.00;comment:玩家的所赢金额" json:"net_amount" db:"net_amount"`                                                                                                 // 玩家的所赢金额
	TotalFanshui   *float64      `gorm:"column:total_fanshui;type:decimal(12,2);comment:返水金额" json:"total_fanshui" db:"total_fanshui"`                                                                                                                 // 返水金额
	IsFanshui      int64         `gorm:"column:is_fanshui;type:tinyint;not null;index:adx_date_game_user_fanshui,priority:4;index:is_fanshui_index,priority:1;default:0;comment:0:未返水;1:返水进行中;2:已返水;" json:"is_fanshui" db:"is_fanshui"`               // 0:未返水;1:返水进行中;2:已返水;
	FanshuiAt      *sql.NullTime `gorm:"column:fanshui_at;type:timestamp;index:user_game_bet_amounts_fanshui_at_index,priority:1;comment:返水时间" json:"fanshui_at" db:"fanshui_at"`                                                                      // 返水时间
	IsManual       *int64        `gorm:"column:is_manual;type:tinyint;comment:是否手动返水0:否;1:是手动" json:"is_manual" db:"is_manual"`                                                                                                                        // 是否手动返水0:否;1:是手动
	IsOpen         int64         `gorm:"column:is_open;type:tinyint;not null;index:adx_date_game_user_fanshui,priority:5;index:user_game_bet_amounts_is_open_index,priority:1;default:1;comment:是否启用0:否;1:是;如果为0就重新统计打码量" json:"is_open" db:"is_open"` // 是否启用0:否;1:是;如果为0就重新统计打码量
	IsYongjin      *int64        `gorm:"column:is_yongjin;type:tinyint;index:adx_date_game_user_fanshui,priority:6;index:adx_yongjin_date,priority:1;comment:是否统计了代理佣金0否，1进行中；2:已经返佣" json:"is_yongjin" db:"is_yongjin"`                               // 是否统计了代理佣金0否，1进行中；2:已经返佣
	IsTotalBet     *int64        `gorm:"column:is_total_bet;type:tinyint;index:adx_date_game_user_fanshui,priority:7;index:is_total_bet,priority:1;comment:是否统计到总注单表：0否，1进行中；2:已统计" json:"is_total_bet" db:"is_total_bet"`                             // 是否统计到总注单表：0否，1进行中；2:已统计
	IsTodayProfit  *int64        `gorm:"column:is_today_profit;type:tinyint;index:is_today_profit,priority:1;comment:是否统计到今日盈亏表：0否，1进行中；2:已统计；today_profits" json:"is_today_profit" db:"is_today_profit"`                                              // 是否统计到今日盈亏表：0否，1进行中；2:已统计；today_profits
	IsDeleted      *int64        `gorm:"column:is_deleted;type:tinyint;comment:是否删除0:否;1:已删除" json:"is_deleted" db:"is_deleted"`                                                                                                                       // 是否删除0:否;1:已删除
	CreatedAt      *sql.NullTime `gorm:"column:created_at;type:bigint;autoCreateTime:milli" json:"created_at" db:"created_at"`
	UpdatedAt      *sql.NullTime `gorm:"column:updated_at;type:bigint;autoUpdateTime:milli" json:"updated_at" db:"updated_at"`
}

// TableName UserGameBetAmountsCopy's table name
func (*UserGameBetAmountsCopy) TableName() string {
	return TableNameUserGameBetAmountsCopy
}
