// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/davy66666/rpc_common/dao/model"
)

func newMatchesCopy1(db *gorm.DB, opts ...gen.DOOption) matchesCopy1 {
	_matchesCopy1 := matchesCopy1{}

	_matchesCopy1.matchesCopy1Do.UseDB(db, opts...)
	_matchesCopy1.matchesCopy1Do.UseModel(&model.MatchesCopy1{})

	tableName := _matchesCopy1.matchesCopy1Do.TableName()
	_matchesCopy1.ALL = field.NewAsterisk(tableName)
	_matchesCopy1.ID = field.NewInt64(tableName, "id")
	_matchesCopy1.MatchEventID = field.NewInt64(tableName, "match_event_id")
	_matchesCopy1.MatchEventParentID = field.NewInt64(tableName, "match_event_parent_id")
	_matchesCopy1.Group = field.NewString(tableName, "group")
	_matchesCopy1.Round = field.NewInt64(tableName, "round")
	_matchesCopy1.HomeID = field.NewInt64(tableName, "home_id")
	_matchesCopy1.HomeName = field.NewString(tableName, "home_name")
	_matchesCopy1.HomeGoal = field.NewInt64(tableName, "home_goal")
	_matchesCopy1.AwayID = field.NewInt64(tableName, "away_id")
	_matchesCopy1.AwayName = field.NewString(tableName, "away_name")
	_matchesCopy1.AwayGoal = field.NewInt64(tableName, "away_goal")
	_matchesCopy1.MatchTime = field.NewField(tableName, "match_time")
	_matchesCopy1.GuessHomeWinAmount = field.NewInt64(tableName, "guess_home_win_amount")
	_matchesCopy1.GuessAwayWinAmount = field.NewInt64(tableName, "guess_away_win_amount")
	_matchesCopy1.GuessTieAmount = field.NewInt64(tableName, "guess_tie_amount")
	_matchesCopy1.CreatedAt = field.NewField(tableName, "created_at")
	_matchesCopy1.UpdatedAt = field.NewField(tableName, "updated_at")
	_matchesCopy1.Status = field.NewInt64(tableName, "status")
	_matchesCopy1.MinBet = field.NewFloat64(tableName, "min_bet")
	_matchesCopy1.MaxBet = field.NewFloat64(tableName, "max_bet")
	_matchesCopy1.HomeOdds = field.NewFloat64(tableName, "home_odds")
	_matchesCopy1.AwayOdds = field.NewFloat64(tableName, "away_odds")
	_matchesCopy1.DrawOdds = field.NewFloat64(tableName, "draw_odds")
	_matchesCopy1.IsOpen = field.NewInt64(tableName, "is_open")
	_matchesCopy1.StopBetAt = field.NewField(tableName, "stop_bet_at")
	_matchesCopy1.AdminName = field.NewString(tableName, "admin_name")

	_matchesCopy1.fillFieldMap()

	return _matchesCopy1
}

// matchesCopy1 比赛列表
type matchesCopy1 struct {
	matchesCopy1Do matchesCopy1Do

	ALL                field.Asterisk
	ID                 field.Int64
	MatchEventID       field.Int64   // 赛程ID
	MatchEventParentID field.Int64   // 赛程上级ID
	Group              field.String  // 组别
	Round              field.Int64   // 场次
	HomeID             field.Int64   // 主队ID
	HomeName           field.String  // 主队名称
	HomeGoal           field.Int64   // 主队进球
	AwayID             field.Int64   // 客队ID
	AwayName           field.String  // 客队名称
	AwayGoal           field.Int64   // 客队进球
	MatchTime          field.Field   // 开赛时间
	GuessHomeWinAmount field.Int64   // 猜主队赢总数
	GuessAwayWinAmount field.Int64   // 客队赢总数
	GuessTieAmount     field.Int64   // 猜平数
	CreatedAt          field.Field   // 创建时间
	UpdatedAt          field.Field   // 更新时间
	Status             field.Int64   // 是否结算 0:未结算 1:已结算
	MinBet             field.Float64 // 最低投注金额
	MaxBet             field.Float64 // 最高投注金额
	HomeOdds           field.Float64 // 主胜赔率
	AwayOdds           field.Float64 // 客胜赔率
	DrawOdds           field.Float64 // 和局赔率
	IsOpen             field.Int64   // 状态 0:禁用 1:启用
	StopBetAt          field.Field   // 停止投注时间
	AdminName          field.String  // 操作员

	fieldMap map[string]field.Expr
}

func (m matchesCopy1) Table(newTableName string) *matchesCopy1 {
	m.matchesCopy1Do.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m matchesCopy1) As(alias string) *matchesCopy1 {
	m.matchesCopy1Do.DO = *(m.matchesCopy1Do.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *matchesCopy1) updateTableName(table string) *matchesCopy1 {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MatchEventID = field.NewInt64(table, "match_event_id")
	m.MatchEventParentID = field.NewInt64(table, "match_event_parent_id")
	m.Group = field.NewString(table, "group")
	m.Round = field.NewInt64(table, "round")
	m.HomeID = field.NewInt64(table, "home_id")
	m.HomeName = field.NewString(table, "home_name")
	m.HomeGoal = field.NewInt64(table, "home_goal")
	m.AwayID = field.NewInt64(table, "away_id")
	m.AwayName = field.NewString(table, "away_name")
	m.AwayGoal = field.NewInt64(table, "away_goal")
	m.MatchTime = field.NewField(table, "match_time")
	m.GuessHomeWinAmount = field.NewInt64(table, "guess_home_win_amount")
	m.GuessAwayWinAmount = field.NewInt64(table, "guess_away_win_amount")
	m.GuessTieAmount = field.NewInt64(table, "guess_tie_amount")
	m.CreatedAt = field.NewField(table, "created_at")
	m.UpdatedAt = field.NewField(table, "updated_at")
	m.Status = field.NewInt64(table, "status")
	m.MinBet = field.NewFloat64(table, "min_bet")
	m.MaxBet = field.NewFloat64(table, "max_bet")
	m.HomeOdds = field.NewFloat64(table, "home_odds")
	m.AwayOdds = field.NewFloat64(table, "away_odds")
	m.DrawOdds = field.NewFloat64(table, "draw_odds")
	m.IsOpen = field.NewInt64(table, "is_open")
	m.StopBetAt = field.NewField(table, "stop_bet_at")
	m.AdminName = field.NewString(table, "admin_name")

	m.fillFieldMap()

	return m
}

func (m *matchesCopy1) WithContext(ctx context.Context) IMatchesCopy1Do {
	return m.matchesCopy1Do.WithContext(ctx)
}

func (m matchesCopy1) TableName() string { return m.matchesCopy1Do.TableName() }

func (m matchesCopy1) Alias() string { return m.matchesCopy1Do.Alias() }

func (m matchesCopy1) Columns(cols ...field.Expr) gen.Columns {
	return m.matchesCopy1Do.Columns(cols...)
}

func (m *matchesCopy1) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *matchesCopy1) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 26)
	m.fieldMap["id"] = m.ID
	m.fieldMap["match_event_id"] = m.MatchEventID
	m.fieldMap["match_event_parent_id"] = m.MatchEventParentID
	m.fieldMap["group"] = m.Group
	m.fieldMap["round"] = m.Round
	m.fieldMap["home_id"] = m.HomeID
	m.fieldMap["home_name"] = m.HomeName
	m.fieldMap["home_goal"] = m.HomeGoal
	m.fieldMap["away_id"] = m.AwayID
	m.fieldMap["away_name"] = m.AwayName
	m.fieldMap["away_goal"] = m.AwayGoal
	m.fieldMap["match_time"] = m.MatchTime
	m.fieldMap["guess_home_win_amount"] = m.GuessHomeWinAmount
	m.fieldMap["guess_away_win_amount"] = m.GuessAwayWinAmount
	m.fieldMap["guess_tie_amount"] = m.GuessTieAmount
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["status"] = m.Status
	m.fieldMap["min_bet"] = m.MinBet
	m.fieldMap["max_bet"] = m.MaxBet
	m.fieldMap["home_odds"] = m.HomeOdds
	m.fieldMap["away_odds"] = m.AwayOdds
	m.fieldMap["draw_odds"] = m.DrawOdds
	m.fieldMap["is_open"] = m.IsOpen
	m.fieldMap["stop_bet_at"] = m.StopBetAt
	m.fieldMap["admin_name"] = m.AdminName
}

func (m matchesCopy1) clone(db *gorm.DB) matchesCopy1 {
	m.matchesCopy1Do.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m matchesCopy1) replaceDB(db *gorm.DB) matchesCopy1 {
	m.matchesCopy1Do.ReplaceDB(db)
	return m
}

type matchesCopy1Do struct{ gen.DO }

type IMatchesCopy1Do interface {
	gen.SubQuery
	Debug() IMatchesCopy1Do
	WithContext(ctx context.Context) IMatchesCopy1Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMatchesCopy1Do
	WriteDB() IMatchesCopy1Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMatchesCopy1Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMatchesCopy1Do
	Not(conds ...gen.Condition) IMatchesCopy1Do
	Or(conds ...gen.Condition) IMatchesCopy1Do
	Select(conds ...field.Expr) IMatchesCopy1Do
	Where(conds ...gen.Condition) IMatchesCopy1Do
	Order(conds ...field.Expr) IMatchesCopy1Do
	Distinct(cols ...field.Expr) IMatchesCopy1Do
	Omit(cols ...field.Expr) IMatchesCopy1Do
	Join(table schema.Tabler, on ...field.Expr) IMatchesCopy1Do
	LeftJoin(table schema.Tabler, on ...field.Expr) IMatchesCopy1Do
	RightJoin(table schema.Tabler, on ...field.Expr) IMatchesCopy1Do
	Group(cols ...field.Expr) IMatchesCopy1Do
	Having(conds ...gen.Condition) IMatchesCopy1Do
	Limit(limit int) IMatchesCopy1Do
	Offset(offset int) IMatchesCopy1Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchesCopy1Do
	Unscoped() IMatchesCopy1Do
	Create(values ...*model.MatchesCopy1) error
	CreateInBatches(values []*model.MatchesCopy1, batchSize int) error
	Save(values ...*model.MatchesCopy1) error
	First() (*model.MatchesCopy1, error)
	Take() (*model.MatchesCopy1, error)
	Last() (*model.MatchesCopy1, error)
	Find() ([]*model.MatchesCopy1, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MatchesCopy1, err error)
	FindInBatches(result *[]*model.MatchesCopy1, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MatchesCopy1) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMatchesCopy1Do
	Assign(attrs ...field.AssignExpr) IMatchesCopy1Do
	Joins(fields ...field.RelationField) IMatchesCopy1Do
	Preload(fields ...field.RelationField) IMatchesCopy1Do
	FirstOrInit() (*model.MatchesCopy1, error)
	FirstOrCreate() (*model.MatchesCopy1, error)
	FindByPage(offset int, limit int) (result []*model.MatchesCopy1, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMatchesCopy1Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m matchesCopy1Do) Debug() IMatchesCopy1Do {
	return m.withDO(m.DO.Debug())
}

func (m matchesCopy1Do) WithContext(ctx context.Context) IMatchesCopy1Do {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m matchesCopy1Do) ReadDB() IMatchesCopy1Do {
	return m.Clauses(dbresolver.Read)
}

func (m matchesCopy1Do) WriteDB() IMatchesCopy1Do {
	return m.Clauses(dbresolver.Write)
}

func (m matchesCopy1Do) Session(config *gorm.Session) IMatchesCopy1Do {
	return m.withDO(m.DO.Session(config))
}

func (m matchesCopy1Do) Clauses(conds ...clause.Expression) IMatchesCopy1Do {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m matchesCopy1Do) Returning(value interface{}, columns ...string) IMatchesCopy1Do {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m matchesCopy1Do) Not(conds ...gen.Condition) IMatchesCopy1Do {
	return m.withDO(m.DO.Not(conds...))
}

func (m matchesCopy1Do) Or(conds ...gen.Condition) IMatchesCopy1Do {
	return m.withDO(m.DO.Or(conds...))
}

func (m matchesCopy1Do) Select(conds ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.Select(conds...))
}

func (m matchesCopy1Do) Where(conds ...gen.Condition) IMatchesCopy1Do {
	return m.withDO(m.DO.Where(conds...))
}

func (m matchesCopy1Do) Order(conds ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.Order(conds...))
}

func (m matchesCopy1Do) Distinct(cols ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m matchesCopy1Do) Omit(cols ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.Omit(cols...))
}

func (m matchesCopy1Do) Join(table schema.Tabler, on ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.Join(table, on...))
}

func (m matchesCopy1Do) LeftJoin(table schema.Tabler, on ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m matchesCopy1Do) RightJoin(table schema.Tabler, on ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m matchesCopy1Do) Group(cols ...field.Expr) IMatchesCopy1Do {
	return m.withDO(m.DO.Group(cols...))
}

func (m matchesCopy1Do) Having(conds ...gen.Condition) IMatchesCopy1Do {
	return m.withDO(m.DO.Having(conds...))
}

func (m matchesCopy1Do) Limit(limit int) IMatchesCopy1Do {
	return m.withDO(m.DO.Limit(limit))
}

func (m matchesCopy1Do) Offset(offset int) IMatchesCopy1Do {
	return m.withDO(m.DO.Offset(offset))
}

func (m matchesCopy1Do) Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchesCopy1Do {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m matchesCopy1Do) Unscoped() IMatchesCopy1Do {
	return m.withDO(m.DO.Unscoped())
}

func (m matchesCopy1Do) Create(values ...*model.MatchesCopy1) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m matchesCopy1Do) CreateInBatches(values []*model.MatchesCopy1, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m matchesCopy1Do) Save(values ...*model.MatchesCopy1) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m matchesCopy1Do) First() (*model.MatchesCopy1, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MatchesCopy1), nil
	}
}

func (m matchesCopy1Do) Take() (*model.MatchesCopy1, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MatchesCopy1), nil
	}
}

func (m matchesCopy1Do) Last() (*model.MatchesCopy1, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MatchesCopy1), nil
	}
}

func (m matchesCopy1Do) Find() ([]*model.MatchesCopy1, error) {
	result, err := m.DO.Find()
	return result.([]*model.MatchesCopy1), err
}

func (m matchesCopy1Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MatchesCopy1, err error) {
	buf := make([]*model.MatchesCopy1, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m matchesCopy1Do) FindInBatches(result *[]*model.MatchesCopy1, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m matchesCopy1Do) Attrs(attrs ...field.AssignExpr) IMatchesCopy1Do {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m matchesCopy1Do) Assign(attrs ...field.AssignExpr) IMatchesCopy1Do {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m matchesCopy1Do) Joins(fields ...field.RelationField) IMatchesCopy1Do {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m matchesCopy1Do) Preload(fields ...field.RelationField) IMatchesCopy1Do {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m matchesCopy1Do) FirstOrInit() (*model.MatchesCopy1, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MatchesCopy1), nil
	}
}

func (m matchesCopy1Do) FirstOrCreate() (*model.MatchesCopy1, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MatchesCopy1), nil
	}
}

func (m matchesCopy1Do) FindByPage(offset int, limit int) (result []*model.MatchesCopy1, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m matchesCopy1Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m matchesCopy1Do) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m matchesCopy1Do) Delete(models ...*model.MatchesCopy1) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *matchesCopy1Do) withDO(do gen.Dao) *matchesCopy1Do {
	m.DO = *do.(*gen.DO)
	return m
}
